(function(){
const db=window.bsanDb,id=p=>`${p}-${String(new Date().getDate()).padStart(2,'0')}${String(new Date().getMonth()+1).padStart(2,'0')}-${Math.floor(1000+Math.random()*9000)}`;
async function all(t,c='*',fn=q=>q){let o=[];for(let a=0;;a+=1000){const{data,error}=await fn(db.from(t).select(c).range(a,a+999));if(error)throw error;o.push(...data);if(data.length<1000)return o}}
async function profile(){const{data:{user},error}=await db.auth.getUser();if(error||!user)throw new Error('Sesi tidak aktif');const{data:p,error:e}=await db.from('profiles').select('*').eq('auth_user_id',user.id).maybeSingle();if(e)throw e;return p}
async function current(){const p=await profile();if(!p?.bsan_role)return{success:false};return{success:true,user:{role:p.bsan_role,username:p.legacy_username,nama:p.nama,divisi:p.bsan_divisi||'Umum'}}}
async function upload(arr,prefix){if(!arr)return'-';if(typeof arr==='string')arr=[arr];if(!window.SiagaDrive)throw new Error('Penghubung Google Drive belum dimuat');const out=[];let i=0;for(const x of arr){if(!x||x==='-')continue;if(x.startsWith('http')){out.push(x);continue}if(x.startsWith('data:')){i++;const mime=(x.match(/^data:([^;,]+)/)||[])[1]||'application/octet-stream';const uploaded=await window.SiagaDrive.uploadDataUrl(db,x,{app:'bsan',category:prefix,mimeType:mime});out.push(uploaded.url)}}return out.join(', ')||'-'}
async function resolve(s){if(!s||s==='-')return s||'-';const parts=String(s).split(', ').filter(Boolean);return(await Promise.all(parts.map(async x=>{if(!x.startsWith('storage:'))return x;const{data}=await db.storage.from('bsan-files').createSignedUrl(x.slice(8),3600);return data?.signedUrl||''}))).filter(Boolean).join(', ')}
async function insert(table,row,msg){const{error}=await db.from(table).insert(row);if(error)throw error;return{success:true,message:msg,id:row.id}}
async function submitAduan(d){const x=id('ADU');return insert('bsan_complaints',{id:x,reporter_id:d.isAnonim?'ANONIM':d.nisn||'-',reporter_name:d.isAnonim?'Rahasia':d.nama,kelas:d.kelas||'-',kategori:d.kategori,kronologi:d.kronologi,evidence_urls:await upload(d.bukti,'aduan/'+x),status:'Menunggu Penanganan'},'Laporan dicatat dengan aman dan rahasia.')}
async function submitBK(d){return insert('bsan_counseling',{id:id('BK'),student_id:d.nisn||'-',student_name:d.nama,kelas:d.kelas,tanggal:d.tanggal,sesi:d.sesi,topik:d.topik,status:'Menunggu Konfirmasi'},'Jadwal BK terkirim.')}
async function submitSarpras(d){const x=id('SAR');return insert('bsan_facilities',{id:x,pelapor:d.pelapor,lokasi:d.lokasi,kerusakan:d.jenis,deskripsi:d.deskripsi,evidence_urls:await upload(d.bukti,'sarpras/'+x),status:'Dilaporkan'},'Laporan kerusakan dicatat tim.')}
async function submitRefleksi(d){return insert('bsan_reflections',{id:id('REF'),student_id:d.nisn||'-',student_name:d.nama,kelas:d.kelas,emosi:d.emosi,catatan:d.catatan,kendala:d.kendala||'-'},'Refleksi harian terekam!')}
async function submitKudos(d){return insert('bsan_kudos',{id:id('KUD'),dari:d.dari,untuk:d.untuk,pesan:d.pesan,kategori:d.kategori,status:'Disetujui'},'Kudos dikirim ke wall apresiasi!')}
const done=s=>String(s||'').includes('Selesai')||String(s||'').includes('Diperbaiki');
async function publicFeed(){const{data,error}=await db.rpc('get_bsan_public_feed');if(error)throw error;return{success:true,...data}}
async function tracking(d){const{data,error}=await db.rpc('get_bsan_tracking',{p_id:d.searchId});if(error)throw error;return{success:true,...data}}
async function workspace(d){const[p,task,t,f,j,a,s,k]=await Promise.all([all('bsan_programs'),all('bsan_tasks'),all('bsan_findings'),all('bsan_facilities'),all('bsan_team_journals'),all('bsan_complaints'),all('bsan_facilities'),all('bsan_kudos')]),r=(d.role||'').toLowerCase(),dv=(d.divisi||'').toLowerCase(),full=r.includes('kepala')||r.includes('admin')||r.includes('pengawas')||['ketua','penanggung jawab','monev','pengawas'].some(x=>dv.includes(x)),proker=p.filter(x=>full||String(x.divisi).toLowerCase()===dv).map(x=>({id:x.id,nama:x.nama,divisi:x.divisi,indikator:x.tujuan,pj:x.pj,status:x.status})),tugas=await Promise.all(task.filter(x=>full||proker.some(p=>p.id===x.program_id)||String(x.penerima).toLowerCase().includes(dv)).map(async x=>({id:x.id,waktu:x.created_at,id_program:x.program_id,nama:x.nama,penerima:x.penerima,deadline:x.deadline,status:x.status,bukti:await resolve(x.evidence_urls)}))),temuan=await Promise.all(t.filter(x=>full||String(x.divisi_tujuan).toLowerCase()===dv).map(async x=>({id:x.id,waktu:x.created_at,kategori:x.kategori,lokasi:x.lokasi,deskripsi:x.deskripsi,prioritas:x.prioritas,tl_divisi:x.divisi_tujuan,status:x.status,buktiAwal:await resolve(x.evidence_awal),buktiTL:await resolve(x.evidence_perbaikan)}))),port=[];for(const x of j)if(x.dokumentasi&&x.dokumentasi!=='-')port.push({id:x.id,sumber:'Jurnal Divisi',waktu:x.created_at,divisi:x.divisi,deskripsi:x.kegiatan,urls:await resolve(x.dokumentasi)});return{success:true,data:{tugas:tugas.reverse(),proker:proker.reverse(),temuan:temuan.reverse(),portofolio:port.reverse(),statistik:{prokerSelesai:p.filter(x=>done(x.status)).length,aduanAktif:a.filter(x=>!done(x.status)).length,aduanSelesai:a.filter(x=>done(x.status)).length,sarprasAktif:s.filter(x=>!done(x.status)).length,sarprasSelesai:s.filter(x=>done(x.status)).length,temuanAmanAktif:t.filter(x=>x.kategori==='Keamanan'&&!done(x.status)).length,temuanAmanSelesai:t.filter(x=>x.kategori==='Keamanan'&&done(x.status)).length,temuanNyamanAktif:t.filter(x=>x.kategori!=='Keamanan'&&!done(x.status)).length,temuanNyamanSelesai:t.filter(x=>x.kategori!=='Keamanan'&&done(x.status)).length,totalKudos:k.length}}}}
async function createProker(d){return insert('bsan_programs',{id:id('PRG'),nama:d.nama,divisi:d.divisi,tujuan:d.indikator,periode:d.periode,target:d.target,pj:d.pj,status:'Berjalan'},'Program kerja baru berhasil dibuat.')}
async function createTugas(d){return insert('bsan_tasks',{id:id('TGS'),program_id:d.id_program,nama:d.nama,penerima:d.penerima,deadline:d.deadline,status:'Belum Dimulai',evidence_urls:'-'},'Tugas berhasil didelegasikan.')}
async function createTemuan(d){const x=id('TMN');return insert('bsan_findings',{id:x,kategori:d.kategori,lokasi:d.lokasi,deskripsi:d.deskripsi,prioritas:d.prioritas,divisi_tujuan:d.tldivisi,status:'Baru Ditemukan',evidence_awal:await upload(d.buktiAwal,'temuan/'+x),evidence_perbaikan:'-'},'Temuan berhasil dicatat.')}
async function jurnal(d){const x=id('JRN');return insert('bsan_team_journals',{id:x,petugas:d.petugas,divisi:d.divisi,program_id:d.id_program,kegiatan:d.kegiatan,uraian:d.uraian,hasil:d.hasil,kendala:d.kendala,tindak_lanjut:d.tindaklanjut,dokumentasi:await upload(d.dokumentasi,'jurnal/'+x)},'Jurnal tersimpan.')}
async function updateTugas(d){const v={status:d.status};if(d.bukti?.length)v.evidence_urls=await upload(d.bukti,'tugas/'+d.id);const{error}=await db.from('bsan_tasks').update(v).eq('id',d.id);if(error)throw error;return{success:true,message:'Progress tugas diupdate.'}}
async function updateTemuan(d){const v={status:d.status};if(d.buktiTL?.length)v.evidence_perbaikan=await upload(d.buktiTL,'temuan-tl/'+d.id);const{error}=await db.from('bsan_findings').update(v).eq('id',d.id);if(error)throw error;return{success:true,message:'Status temuan diperbarui.'}}
async function aduan(d){const allow=['kepala','admin','pengawas','bk'].some(x=>(d.role||'').toLowerCase().includes(x))||['penanggung jawab','ketua','pengawas','perlindungan','sekretaris'].some(x=>(d.divisi||'').toLowerCase().includes(x));if(!allow)return{success:false,message:'Akses Ditolak. Area Sensitif.'};const a=await all('bsan_complaints','*',q=>q.order('created_at',{ascending:false}));return{success:true,data:await Promise.all(a.map(async x=>({id:x.id,waktu:x.created_at,pelapor:x.reporter_name,kelas:x.kelas,kategori:x.kategori,kronologi:x.kronologi,bukti:await resolve(x.evidence_urls),status:x.status})))}}
async function updateStatus(d){const map={ADUAN:'bsan_complaints',SARPRAS:'bsan_facilities',BK:'bsan_counseling',TEMUAN:'bsan_findings'},table=map[d.sheetKey];if(!table)return{success:false};const{error}=await db.from(table).update({status:d.status}).eq('id',d.id);if(error)throw error;return{success:true,message:'Status berhasil diubah.'}}
const h={getCurrentUser:current,submitAduan,submitJanjiBK:submitBK,submitSarpras,submitRefleksi,submitKudos,getPublicFeed:publicFeed,checkTrackingStatus:tracking,getWorkspaceData:workspace,getAduanMasuk:aduan,createProker,createTugas,createTemuan,submitJurnalTim:jurnal,updateTugasBukti:updateTugas,updateTemuanBukti:updateTemuan,updateStatusRecord:updateStatus};
window.bsanApi=async(a,d={})=>{try{return h[a]?await h[a](d):{success:false,message:'Action tidak dikenal'}}catch(e){console.error(e);return{success:false,message:e.message}}};
})();
