(function(){
const db=window.supervisiDb,success=(data={})=>({status:'success',...data});
async function all(t,c='*',fn=q=>q){let o=[];for(let a=0;;a+=1000){const{data,error}=await fn(db.from(t).select(c).range(a,a+999));if(error)throw error;o.push(...data);if(data.length<1000)return o}}
async function profile(){const{data:{user},error}=await db.auth.getUser();if(error||!user)throw new Error('Sesi tidak aktif');const{data:p,error:e}=await db.from('profiles').select('*').eq('auth_user_id',user.id).single();if(e)throw e;return p}
const usr=p=>({id:p.teacher_id,username:p.legacy_username,nama:p.nama,role:p.supervisi_role||'Guru',mapel:p.mata_pelajaran||'-'});
async function url(x){if(!x.storage_path)return x.legacy_url||'';const{data}=await db.storage.from('supervisi-files').createSignedUrl(x.storage_path,3600);return data?.signedUrl||''}
async function current(){return success({user:usr(await profile())})}
async function guru(){const p=await all('profiles','legacy_username,nama,supervisi_role,mata_pelajaran',q=>q.not('supervisi_role','is',null));return success({data:p.filter(x=>x.supervisi_role!=='Admin').map(x=>({username:x.legacy_username,nama:x.nama,mapel:x.mata_pelajaran,role:x.supervisi_role}))})}
async function rubrik(d){return success({data:await all('supervision_rubrics','*',q=>d.jenis?q.ilike('jenis',d.jenis):q).then(a=>a.map(x=>({id:x.id,jenis:x.jenis,kategori:x.kategori,indikator:x.indikator})))})}
async function dokumen(d){const a=await all('teacher_documents','*',q=>q.eq('username_guru',d.username).order('tanggal',{ascending:false}));return success({data:await Promise.all(a.map(async x=>({id:x.id,kategori:x.kategori,nama:x.nama,jenis:x.jenis,url:await url(x),status:x.status,tanggal:x.tanggal})))})}
async function saveDok(d){let fileUrl=d.url||null;if(d.tipe==='file'&&d.fileData){if(!window.SiagaDrive)throw new Error('Penghubung Google Drive belum dimuat');const uploaded=await window.SiagaDrive.uploadBase64(db,d.fileData,{app:'supervisi',category:d.username||'guru',fileName:d.fileName,mimeType:d.fileMimeType});fileUrl=uploaded.viewUrl||uploaded.url}const{error}=await db.from('teacher_documents').insert({id:'DOK-'+Date.now(),username_guru:d.username,kategori:d.kategori,nama:d.nama,jenis:d.tipe,storage_path:null,legacy_url:fileUrl,status:'Menunggu Review',tanggal:new Date().toISOString().slice(0,10)});if(error)throw error;return success({message:'Dokumen berhasil disimpan'})}
async function updateDok(d){const{error}=await db.from('teacher_documents').update({status:d.status}).eq('id',d.idDok);if(error)throw error;return success({message:'Status berhasil diperbarui!'})}
async function diskusi(d){const a=await all('document_discussions','*',q=>q.eq('document_id',d.idDok).order('created_at'));return success({data:a.map(x=>({id:x.id,pengirim:x.nama_pengirim,role:x.role_pengirim,pesan:x.komentar,waktu:new Date(x.created_at).toLocaleString('id-ID')}))})}
async function komentar(d){const{error}=await db.from('document_discussions').insert({id:'DSK-'+Date.now(),document_id:d.idDok,nama_pengirim:d.nama,role_pengirim:d.role,komentar:d.pesan});if(error)throw error;return diskusi(d)}
async function ajukan(d){const{error}=await db.from('supervision_sessions').insert({id:'SUP-'+Date.now(),username_guru:d.usernameGuru,username_supervisor:d.usernameSupervisor,tanggal:d.tanggal,mapel:d.mapel,fase:'Pra',document_rpp_id:d.idDokumenRPP||null});if(error)throw error;return success({message:'Jadwal berhasil diajukan!'})}
async function jadwal(d){const wide=['Kepsek','Kepala Sekolah','Waka_Kurikulum','Waka Kurikulum','Pengawas'].includes(d.role),[a,ps]=await Promise.all([all('supervision_sessions','*',q=>q.order('tanggal',{ascending:false})),all('profiles','legacy_username,nama')]),names=Object.fromEntries(ps.map(x=>[x.legacy_username,x.nama]));return success({data:a.filter(x=>wide||x.username_guru===d.username||x.username_supervisor===d.username).map(x=>({id:x.id,usernameGuru:x.username_guru,namaGuru:names[x.username_guru]||x.username_guru,usernameSupervisor:x.username_supervisor,namaSupervisor:names[x.username_supervisor]||x.username_supervisor,tanggal:x.tanggal,mapel:x.mapel,fase:x.fase,praTujuan:x.pra_tujuan,praFokus:x.pra_fokus,obsCatatan:x.obs_catatan,pascaRefleksi:x.pasca_refleksi,idDokumenRPP:x.document_rpp_id||''}))})}
async function fase(d){let v={fase:d.fase};if(d.fase==='Pra')v={fase:'Pra',pra_tujuan:d.tujuan,pra_fokus:d.fokus};if(d.fase==='Obs')v={fase:'Obs',obs_catatan:d.catatan||''};if(d.fase==='Pasca')v={fase:'Selesai',pasca_refleksi:d.refleksi||''};const{error}=await db.from('supervision_sessions').update(v).eq('id',d.id);if(error)throw error;return success()}
async function detail(d){const a=await all('assessment_details','*',q=>q.eq('session_id',d.idPendampingan));return success({data:a.map(x=>({id:x.id,idPendampingan:x.session_id,idKriteria:x.rubric_id,skor:x.skor,catatan:x.catatan}))})}
async function saveDetail(d){for(const x of d.items||[]){const row={id:`DTL-${d.idPendampingan}-${x.idKriteria}`,session_id:d.idPendampingan,rubric_id:x.idKriteria,skor:x.skor,catatan:x.catatan};const{error}=await db.from('assessment_details').upsert(row,{onConflict:'session_id,rubric_id'});if(error)throw error}return success({message:'Penilaian rubrik berhasil disimpan!'})}
const h={getCurrentUser:current,getGuruList:guru,getRubrik:rubrik,getDokumen:dokumen,saveDokumen:saveDok,updateStatusDokumen:updateDok,getDiskusi:diskusi,kirimKomentar:komentar,ajukanJadwal:ajukan,getJadwal:jadwal,updateFase:fase,getDetailPenilaian:detail,saveDetailPenilaian:saveDetail};
window.supervisiApi=async(a,d={})=>{try{return h[a]?await h[a](d):{status:'error',message:'Action tidak dikenal'}}catch(e){console.error(e);return{status:'error',message:e.message}}};
})();
