(function(){
const db=window.mengajarDb;
const MAPEL=["Bahasa Indonesia","Bahasa Inggris","Dasar-Dasar Agribisnis","Informatika","IPAS","Konsentrasi Keahlian","Matematika","Pendidikan Agama Islam","Pendidikan Agama Kristen","Pendidikan Agama Hindu","Pendidikan Pancasila","PJOK","PKK","PKWU","Projek IPAS","Sejarah","Seni Budaya"];
async function all(table,cols='*',fn=q=>q){let out=[];for(let a=0;;a+=1000){let q=fn(db.from(table).select(cols).range(a,a+999));const{data,error}=await q;if(error)throw error;out.push(...data);if(data.length<1000)return out}}
async function profile(){const{data:{user},error}=await db.auth.getUser();if(error||!user)throw new Error('Sesi login tidak aktif');const{data:p,error:e}=await db.from('profiles').select('*').eq('auth_user_id',user.id).single();if(e)throw e;return p}
const user=p=>({id:p.teacher_id,nama:p.nama,username:p.legacy_username,role:p.mengajar_role||'Guru'});
async function students(k){return all('profiles','nis,nama,kelas',q=>q.eq('role','SISWA').eq('kelas',k).order('nama')).then(x=>x.map(s=>({nis:s.nis,nama:s.nama})))}
async function current(){return{success:true,user:user(await profile())}}
async function schedules(d){let q=x=>x.order('kelas').order('mapel');if(d.role!=='Admin')q=x=>x.eq('teacher_id',d.idGuru).order('kelas').order('mapel');return all('mengajar_jadwal','kelas,mapel',q)}
async function nilaiExisting(d){const a=await all('mengajar_nilai','nis,nilai',q=>q.eq('kelas',d.kelas).eq('mapel',d.mapel).eq('jenis_tugas',d.jenisTugas));return Object.fromEntries(a.map(x=>[x.nis,x.nilai]))}
async function saveNilai(d){for(const s of d.siswa||[]){const row={created_at:new Date().toISOString(),tanggal:d.tanggal,teacher_id:d.idGuru,kelas:d.kelas,mapel:d.mapel,jenis_tugas:d.jenisTugas,nis:String(s.nis),nilai:Number(s.nilai||0)};const{data}=await db.from('mengajar_nilai').select('id').eq('kelas',d.kelas).eq('mapel',d.mapel).eq('jenis_tugas',d.jenisTugas).eq('nis',String(s.nis)).maybeSingle();const r=data?await db.from('mengajar_nilai').update(row).eq('id',data.id):await db.from('mengajar_nilai').insert(row);if(r.error)throw r.error}return{success:true,message:'Nilai berhasil disimpan.'}}
async function saveAbsen(d){const rows=(d.siswa||[]).map(s=>({tanggal:d.tanggal,teacher_id:d.idGuru,kelas:d.kelas,mapel:d.mapel,nis:String(s.nis),status:s.status}));const{error}=await db.from('mengajar_absensi').insert(rows);if(error)throw error;return{success:true,message:'Presensi berhasil disimpan.'}}
function summary(a){if(!a.length)return'Presensi belum diinput';const names={};return`Hadir: ${a.filter(x=>x.status==='Hadir').length}, Tidak Hadir: ${a.filter(x=>x.status!=='Hadir').length}`}
async function saveJurnal(d){const a=await all('mengajar_absensi','status',q=>q.eq('tanggal',d.tanggal).eq('kelas',d.kelas).eq('mapel',d.mapel));const{error}=await db.from('mengajar_jurnal').insert({tanggal:d.tanggal,teacher_id:d.idGuru,kelas:d.kelas,mapel:d.mapel,materi:d.materi,keterangan:d.keterangan||'-',ringkasan_absen:summary(a)});if(error)throw error;return{success:true,message:'Jurnal berhasil disimpan.'}}
async function jurnal(){const[j,p]=await Promise.all([all('mengajar_jurnal','*',q=>q.order('tanggal',{ascending:false})),all('profiles','teacher_id,nama',q=>q.not('teacher_id','is',null))]);const m=Object.fromEntries(p.map(x=>[x.teacher_id,x.nama]));return j.map(x=>({tanggal:x.tanggal,guru:m[x.teacher_id]||x.teacher_id,kelas:x.kelas,mapel:x.mapel,materi:x.materi,keterangan:x.keterangan,absenSummary:x.ringkasan_absen||'Presensi belum diinput'}))}
async function rekapAbsen(d){const[s,a]=await Promise.all([students(d.kelas),all('mengajar_absensi','*',q=>{q=q.eq('kelas',d.kelas).eq('mapel',d.mapel);if(d.startDate)q=q.gte('tanggal',d.startDate);if(d.endDate)q=q.lte('tanggal',d.endDate);return q})]);const dates=new Set(a.map(x=>x.tanggal));return{totalPertemuan:dates.size,siswa:s.map(x=>{const z=a.filter(y=>y.nis===String(x.nis)),c=k=>z.filter(y=>y.status===k).length,H=c('Hadir'),S=c('Sakit'),I=c('Izin'),A=c('Alpa');return{...x,H,S,I,A,persen:dates.size?Math.round(H/dates.size*100)+'%':'0%'}})}}
async function rekapNilai(d){const[s,g]=await Promise.all([students(d.kelas),all('mengajar_nilai','*',q=>q.eq('kelas',d.kelas).eq('mapel',d.mapel))]);const jenis=[...new Set(g.map(x=>x.jenis_tugas))].sort();return{jenisTugasList:jenis,rekapSiswa:s.map(x=>{const z=g.filter(y=>y.nis===String(x.nis)),scores=Object.fromEntries(z.map(y=>[y.jenis_tugas,y.nilai])),v=Object.values(scores).map(Number);return{...x,scores,rataRata:v.length?(v.reduce((a,b)=>a+b,0)/v.length).toFixed(1):'-'}})}}
async function rekapSiswa(d){const g=await all('mengajar_nilai','*',q=>q.eq('kelas',d.kelas));const mine=g.filter(x=>x.nis===String(d.nis)),allTasks=new Map(g.map(x=>[x.mapel+'|'+x.jenis_tugas,{mapel:x.mapel,tugas:x.jenis_tugas}])),done=new Set(mine.map(x=>x.mapel+'|'+x.jenis_tugas));return{nilaiMasuk:mine.map(x=>({mapel:x.mapel,tugas:x.jenis_tugas,nilai:x.nilai})),tugasKosong:[...allTasks].filter(([k])=>!done.has(k)).map(([,v])=>v)}}
async function keaktifan(){const[j,g,p]=await Promise.all([all('mengajar_jurnal'),all('mengajar_nilai'),all('profiles','teacher_id,nama',q=>q.not('teacher_id','is',null))]);const names=Object.fromEntries(p.map(x=>[x.teacher_id,x.nama])),jm={};j.forEach(x=>{const k=x.teacher_id+'|'+x.kelas+'|'+x.mapel;jm[k]=(jm[k]||0)+1});const rekapMengajar=Object.entries(jm).map(([k,n])=>{const[a,b,c]=k.split('|');return{guru:names[a]||a,kelas:b,mapel:c,jumlahPertemuan:n}});const rekapPenilaian=p.map(t=>{const z=g.filter(x=>x.teacher_id===t.teacher_id),c=k=>z.filter(x=>x.jenis_tugas.startsWith(k)).length;return{guru:t.nama,TG:c('TG'),UH:c('UH'),NP:c('NP'),US:c('US'),total:z.length}});return{rekapMengajar,rekapPenilaian}}
async function legerKelas(d){const[s,g]=await Promise.all([students(d.kelas),all('mengajar_nilai','*',q=>q.eq('kelas',d.kelas))]),mapel=[...new Set(g.map(x=>x.mapel))].sort(),avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;return{mapelList:mapel,legerSiswa:s.map(st=>{let total=0,count=0,mapelScores={};for(const m of mapel){const z=g.filter(x=>x.nis===String(st.nis)&&x.mapel===m);if(!z.length){mapelScores[m]='-';continue}const cat=k=>z.filter(x=>x.jenis_tugas.startsWith(k)).map(x=>Number(x.nilai)),v=+(avg(cat('TG'))*.2+avg(cat('UH'))*.2+avg(cat('NP'))*.3+avg(cat('US'))*.3).toFixed(1);mapelScores[m]=v;total+=v;count++}return{...st,mapelScores,totalNilai:total.toFixed(1),rataRata:count?(total/count).toFixed(1):'-'}})}}
async function leger(){const[s,g]=await Promise.all([all('profiles','nis,nama,kelas',q=>q.eq('role','SISWA')),all('mengajar_nilai')]);return{siswa:[['NIS','Nama','Kelas'],...s.map(x=>[x.nis,x.nama,x.kelas])],nilai:g.map(x=>[x.created_at,x.tanggal,x.teacher_id,x.kelas,x.mapel,x.jenis_tugas,x.nis,x.nilai])}}
const handlers={getCurrentUser:current,getKelas:async()=>[...new Set((await all('profiles','kelas',q=>q.eq('role','SISWA'))).map(x=>x.kelas))].sort(),getDaftarMapel:async()=>MAPEL,getSiswaTamu:async d=>students(d.kelas),getSiswaInput:async d=>students(d.kelas),getRekapTamu:rekapSiswa,getNilaiExisting:nilaiExisting,getJadwal:schedules,simpanNilai:saveNilai,simpanAbsensi:saveAbsen,simpanJurnal:saveJurnal,getJurnalAdmin:jurnal,getRekapAbsen:rekapAbsen,getRekapNilai:rekapNilai,getRekapKeaktifanGuru:keaktifan,getLegerKelasWeighted:legerKelas,getLeger:leger};
window.mengajarApi=async(a,d={})=>{try{if(!handlers[a])throw new Error('Action tidak dikenal: '+a);return await handlers[a](d)}catch(e){console.error(e);return a.startsWith('simpan')?{success:false,message:e.message}:null}};
})();
